blog/blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('posts/', include('post.urls')), 
    path('dashboard/', include('dashboard.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/core/urls.py
from django.urls import path
from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
  path('', views.index, name='index'),
  path('signup/', views.signup, name='signup'),
  path('login/', views.loginUser, name='login'),
  path('logout/', views.logoutUser, name='logout'),
]

blog/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
  path('', views.dashboard, name='dashboard'),
]

blog/post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
  path('', views.browsePost, name='browse'),
  path('<int:pk>', views.detail, name='detail'),
  path('newpost/', views.newPost, name='newpost'),
  path('delete/<int:pk>', views.delete, name='delete'),
  path('edit/<int:pk>', views.edit, name='edit'),
  path('edit/<int:pk>', views.edit, name='edit'),
]

blog/core/models.py
from django.db import models

# Create your models here.

blog/dashboard/models.py
from django.db import models

# Create your models here.

blog/post/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Category(models.Model):
  name = models.CharField(max_length=255)

  class Meta:
    ordering = ['name']
    verbose_name_plural = 'Categories'
  def __str__(self):
    return self.name

class Post(models.Model):
  category = models.ForeignKey(Category, related_name='posts', on_delete=models.CASCADE)
  title = models.CharField(max_length=255)
  description = models.TextField()
  image = models.ImageField(upload_to='post_images', blank=True, null=True)
  created_by = models.ForeignKey(User, related_name='posts', on_delete=models.CASCADE)
  created_at = models.DateTimeField(auto_now_add=True)

  def __str__(self):
    return self.title  

blog/core/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

INPUT_CLASS = 'form-control'


class LoginForm(AuthenticationForm):

  email = forms.CharField(widget=forms.EmailInput(attrs={
    'placeholder': 'Email',
    'class': INPUT_CLASS
  }))

  password = forms.CharField(widget=forms.PasswordInput(attrs={
    'placeholder': 'Password',
    'class': INPUT_CLASS
  }))

  

class SignupForm(UserCreationForm):
  class Meta:
    model = User
    fields = ('first_name', 'last_name', 'email', 'username','password1', 'password2')
  

  first_name = forms.CharField(widget=forms.TextInput(attrs={
    'placeholder': 'First Name',
    'class': INPUT_CLASS
  }))

  last_name = forms.CharField(widget=forms.TextInput(attrs={
    'placeholder': 'Last Name',
    'class': INPUT_CLASS
  }))

  email = forms.CharField(widget=forms.EmailInput(attrs={
    'placeholder': 'Email',
    'class': INPUT_CLASS
  }))

  username = forms.CharField(widget=forms.TextInput(attrs={
    'placeholder': 'Enter a username',
    'class': INPUT_CLASS
  }))

  password1 = forms.CharField(widget=forms.PasswordInput(attrs={
    'placeholder': 'Password',
    'class': INPUT_CLASS
  }))

  password2 = forms.CharField(widget=forms.PasswordInput(attrs={
    'placeholder': 'Confirm Password',
    'class': INPUT_CLASS
  }))

blog/post/forms.py
from django import forms
from .models import Post

INPUT_CLASS = 'form-control'

class newPostForm(forms.ModelForm):
  class Meta:
    model = Post
    fields = ('category', 'title', 'description', 'image')

    widgets = {
      'category': forms.Select(attrs={
        'class': INPUT_CLASS
      }),
      'title': forms.TextInput(attrs={
        'class': INPUT_CLASS
      }),
      'description': forms.Textarea(attrs={
        'class': INPUT_CLASS
      }),
      'image': forms.FileInput(attrs={
        'class': INPUT_CLASS
      })
    }

class editPostForm(forms.ModelForm):
  class Meta:
    model = Post
    fields = ('category', 'title', 'description', 'image')

    widgets = {
      'category': forms.Select(attrs={
        'class': INPUT_CLASS
      }),
      'title': forms.TextInput(attrs={
        'class': INPUT_CLASS
      }),
      'description': forms.Textarea(attrs={
        'class': INPUT_CLASS
      }),
      'image': forms.FileInput(attrs={
        'class': INPUT_CLASS
      })
    }

blog/core/views.py
from django.shortcuts import render, redirect
from post.models import Category, Post
from .forms import SignupForm, LoginForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.models import User

# Create your views here.
def index(request):
  post = Post.objects.all().order_by('-created_at')[0:6]
  category = Category.objects.all()
  context = {
    'posts': post,
    'categories': category,
  }
  return render(request, 'core/index.html', context)

def signup(request):
  if request.method == 'POST':
    form = SignupForm(request.POST)

    if form.is_valid():
      form.save()

      return redirect('/login/')
  
  else:
    form = SignupForm()
  
  context = {
    'form': form,
  }
  return render(request, 'core/signup.html', context)

def loginUser(request):
  if request.method == 'POST':
    email = request.POST.get('email')
    password = request.POST.get('password')
    print(email,' , ', password)
    username = User.objects.filter(email=email).first()
    user = authenticate(request, username=username, password=password)

    if user is None:
      messages.success(request, 'Wrong email and password...')
      return redirect('/login/')
    
    else:
      login(request, user)
      return redirect('/')
    
  else:
    form = LoginForm()
  
  context = {
    'form': form,
  }

  return render(request, 'core/login.html', context)

def logoutUser(request):
  logout(request)
  return redirect('/')

blog/dashboard/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from post.models import Post

# Create your views here.
@login_required
def dashboard(request):
  post = Post.objects.filter(created_by=request.user)
  context = {
    'posts': post,
  }
  return render(request, 'dashboard/dashboard.html', context)

blog/post/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post, Category
from django.contrib.auth.decorators import login_required
from .forms import newPostForm, editPostForm
from django.db.models import Q
# Create your views here.
def browsePost(request):
  query = request.GET.get('query', '')
  category_id = request.GET.get('category', 0)
  categories = Category.objects.all()
  post = Post.objects.all()

  if query:
    post = post.filter(Q(title__icontains=query) | Q(description__icontains=query))

  if category_id:
    post = post.filter(category=category_id)

  context = {
    'posts': post,
    'query': query,
    'categories': categories,
    'category_id': int(category_id),
  }
  return render(request, "post/browsepost.html", context)

def detail(request, pk):
  post = get_object_or_404(Post, pk=pk)
  related_post = Post.objects.filter(category=post.category).exclude(pk=pk)[0:3]
  context = {
    'post': post,
    'related_posts': related_post,
  }

  return render(request, 'post/detail.html', context)

@login_required
def newPost(request):
  if request.method == 'POST':
    form = newPostForm(request.POST, request.FILES)

    if form.is_valid():
      post = form.save(commit=False)
      post.created_by = request.user
      post.save()

      return redirect('post:detail', pk=post.pk)
  
  else:
    form = newPostForm()
  context = {
    'type': 'Add',
    'form': form,
    'title': 'Add Post',
    'btn': 'Add'
  }
  return render(request,'post/newpost.html', context)

@login_required
def edit(request, pk):
  post = get_object_or_404(Post, pk=pk, created_by=request.user)
  # print(post)
  if request.method == 'POST':
    # print('hello')
    form = editPostForm(request.POST, request.FILES, instance=post)
    # print(form)
    if form.is_valid():
      form.save()

      return redirect('post:detail', pk=post.pk)
  else:
    form = editPostForm(instance=post)
  context = {
    'pk': pk,
    'type': 'Edit',
    'form': form,
    'title': 'Edit Post',
    'btn': 'Edit'
  }
  return render(request, 'post/newpost.html', context)

@login_required
def delete(request, pk):
  post = get_object_or_404(Post, pk=pk, created_by=request.user)
  post.delete()
  return redirect('dashboard:dashboard')

 

blog/core/templates/core/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href="/static/css/style.css" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'core:index' %}">My Blog</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse nav justify-content-end" id="navbarSupportedContent">
          <ul class="nav justify-content-end">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'post:newpost' %}">Add Blog</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'post:browse' %}">Browse Blog</a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link btn btn-primary" href="{% url 'dashboard:dashboard' %}">Dashboard</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                {{ request.user.first_name }} {{ request.user.last_name }}
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'core:logout' %}">Log Out</a></li>
              </ul>
            </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link btn btn-primary" href="{% url 'core:login' %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link btn btn-secondary" href="{% url 'core:signup' %}">SignUp</a>
              </li>
            {% endif %}
            
          </ul>
          
        </div>
      </div>
    </nav>
    
    {% block content %}
    {% endblock %}

    <footer class="my-6 bg-dark">
      <div class="container">
        <div class="row">
          <div class="col-lg-6">
            <div class="company-detail text-white">
              <h4>My Blog</h4>
            </div>
          </div>
        </div>
      </div>
    </footer>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

blog/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Home - My Blog{% endblock %}

{% block content %}
<section class="post">
  <div class="container">
    <div class="section-title">
      <h2>Post</h2>
    </div>
    <div class="row">
      {% for post in posts %}
        <div class="col-lg-4">
          <div class="card mb-3" style="width: 18rem;">
            <img src="{{ post.image.url }}" class="card-img-top" alt="{{ post.title }}">
            <div class="card-body">
              <h4 class="card-title">{{ post.title }}</h4>
              <p class="card-text">
                By: {{ post.created_by.first_name }} {{ post.created_by.last_name }}<br>
                At: {{ post.created_at }}
              </p>
              <a href="{% url 'post:detail' post.id %}" class="btn btn-primary">Read Blog</a>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
</section>
<section class="category-section">
  <div class="container">
    <div class="section-title">
      <h2>Categories</h2>
    </div>
    <div class="row">
      {% for category in categories %}
        <div class="col-lg-4">
          <div class="category-card card">
            <h4>{{ category.name }}</h4>
            <p>{{ category.posts.count }}</p>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
</section>
{% endblock %}

blog/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log In - My Blog{% endblock %}

{% block content %}

<section class="signup">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 offset-lg-2 form-con">
        <div class="row">
          <div class="col-lg-6">
            <img src="/static/images/user-img.png" alt="user register" width="100%">
          </div>
          <div class="col-lg-6 form-col">
            <div class="signup-form">
              <h2>Log In</h2>

              {% if messages %}
                {% for message in messages %}
                  <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <strong>{{ message }}</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                  </div>
                {% endfor %}
              {% endif %}

              <form method="post" action=".">
                {% csrf_token %}

                <div class="mb-3">
                  {{ form.email }}
                </div>

                <div class="mb-3">
                  {{ form.password }}
                </div>

                {% if form.errors or form.non_field_errors %}
                <div class="text-danger">
                  {% for field in form %}
                    {{ field.errors }}
                  {% endfor %}

                  {{ form.non_field_errors}}
                </div>
                {% endif %}
                <button class="btn btn-theme-color">LogIn</button>

              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

blog/core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign Up - My Blog{% endblock %}

{% block content %}

<section class="signup">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 offset-lg-2 form-con">
        <div class="row">
          <div class="col-lg-6">
            <img src="/static/images/user-img.png" alt="user register" width="100%">
          </div>
          <div class="col-lg-6 form-col">
            <div class="signup-form">
              <h2>Sign Up</h2>
              <form method="post" action=".">
                {% csrf_token %}

                <div class="mb-3">
                  <!-- <label class="form-label">First Name</label> -->
                  {{ form.first_name }}
                </div>

                <div class="mb-3">
                  {{ form.last_name }}
                </div>

                <div class="mb-3">
                  {{ form.email }}
                </div>

                <div class="mb-3">
                  {{ form.username }}
                </div>

                <div class="mb-3">
                  {{ form.password1 }}
                </div>

                <div class="mb-3">
                  {{ form.password2 }}
                </div>

                {% if form.errors or form.non_field_errors %}
                <div class="text-danger">
                  {% for field in form %}
                    {{ field.errors }}
                  {% endfor %}

                  {{ form.non_field_errors}}
                </div>
                {% endif %}
                <button class="btn btn-theme-color">Submit</button>

              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

blog/dashboard/templates/dashboard/dashboard.html
{% extends 'core/base.html' %}

{% block title %}Dashboard{% endblock %}

{% block content %}
<section class="post">
  <div class="container">
    <div class="section-title">
      <h2>Post</h2>
    </div>
    <div class="row">
      {% for post in posts %}
        <div class="col-lg-4">
          <div class="card mb-3" style="width: 18rem;">
            <img src="{{ post.image.url }}" class="card-img-top" alt="{{ post.title }}">
            <div class="card-body">
              <h4 class="card-title">{{ post.title }}</h4>
              <p class="card-text">
                By: {{ post.created_by.first_name }} {{ post.created_by.last_name }}<br>
                At: {{ post.created_at }}
              </p>
              <a href="{% url 'post:detail' post.id %}" class="btn btn-primary">See Details</a>
              {% if request.user.is_authenticated %}
                <hr class="mb-3">
                <div>
                  <a href="{% url 'post:edit' post.pk %}" class="btn btn-secondary">Edit</a>
                  <a href="{% url 'post:delete' post.pk %}" class="btn btn-danger">Delete</a>
                </div>
              {% endif %}
              
              
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
</section>
{% endblock %}

blog/post/templates/post/browsepost.html
{% extends 'core/base.html' %}

{% block title %}Posts{% endblock %}

{% block content %}
<section>
  <div class="container">
    <div class="row">
      <div class="col-lg-4">
        <form method="get" action="{% url 'post:browse' %}">
          <div>
            <input type="text" class="form-control" name="query" value="{{ query }}" placeholder="Search...">
            <button class="btn mt-3 btn-secondary">Search</button>
          </div>
        </form>
        <hr class="mb-3">
        <p>Categories</p>
        <ul class="search-list">
          {% for category in categories %}
            <li class="{% if category_id == category.id %}active{% endif %}">
              <a href="{% url 'post:browse' %}?query={{ query }}&category={{ category.id }}">{{ category.name }}</a>
            </li>
          {% endfor %}
        </ul>
      </div>
      <div class="col-lg-8">
        <div class="row">
          {% for post in posts %}
            <div class="col-lg-6">
              <div class="card mb-3" style="width: 18rem;">
                <img src="{{ post.image.url }}" class="card-img-top" alt="{{ post.title }}">
                <div class="card-body">
                  <h4 class="card-title">{{ post.title }}</h4>
                  <p class="card-text">
                    By: {{ post.created_by.first_name }} {{ post.created_by.last_name }}<br>
                    At: {{ post.created_at }}
                  </p>
                  <a href="{% url 'post:detail' post.id %}" class="btn btn-primary">Read Blog</a>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

blog/post/templates/post/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
  <section class="post-section">
    <div class="container">
      <div class="row">
        <div class="col-lg-8">
          <div class="post-detail">
            <img src="{{ post.image.url }}" width="100%" class="img-fluid" alt="{{ post.title }}">
            <h4>{{ post.title }}</h4>
            <p>Created By: {{ post.created_by.first_name }} {{ post.created_by.last_name }}<br>
              At: {{ post.created_at }}
            </p>
            <p>{{ post.description }}</p>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="post-side">
            <div class="row">
              {% if request.user.is_authenticated %}
              <div class="col-lg-6">
                <a href="{% url 'post:edit' post.pk %}" class="btn bt-secondary">Edit</a>
              </div>
              <div class="col-lg-6">
                <a href="{% url 'post:delete' post.pk %}" class="btn bt-danger">Delete</a>
              </div>
              {% else %}
                {% for related_post in related_posts %}
                  <div class="col-lg-4">
                    <div class="side-image">
                      <img class="img-thuimbnail" width="100%" src="{{ related_post.image.url }}" alt="{{ related_post.title }}">
                    </div>
                  </div>
                  <div class="col-lg-8">
                    <div class="side-post-detail">
                      <h4><a href="{% url 'post:detail' related_post.pk %}">{{ related_post.title }}</a></h4>
                      <p>Created By: {{ post.created_by.first_name }} {{ post.created_by.last_name }}<br>
                        At: {{ post.created_at }}
                      </p>
                    </div>
                  </div>
                {% endfor %}
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

blog/post/templates/post/newpost.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<section class="itemFormSection">
  <div class="container">
    <div class="section-title">
      <h2>{{ type }} Post</h2>
    </div>
    <form method="post" action="{% if type == 'Edit' %}{% url 'post:edit' pk %}{% else %}.{% endif %}" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}

      {% if form.errors or form.non_field_errors %}
        <div class="text-danger">
          {% for fields in form %}
            {{ field.errors }}
          {% endfor %}
        </div>
      {% endif %}

      <button class="btn btn-primary">{{ btn }} Post</button>
    </form>
  </div>
</section>
{% endblock %}